export enum Token {
    ADD = "ADD",
    SUB = "SUB",
    MUL = "MUL",
    DIV = "DIV",
    INC = "INC",
    DEC = "DEC",
    PUTN = "PUTN",
    PUTS = "PUTS",
    EMIT = "EMIT",
    FPUTN = "FPUTN",
    FPUTS = "FPUTS",
    PUSH = "PUSH",
    DUP = "DUP",
    SWAP = "SWAP",
    DROP = "DROP",
    OVER = "OVER",
    ROT = "ROT",
    EQUAL = "EQUAL",
    FUN = "FUN",
    DO = "DO",
    END = "END",
    PEEK = "PEEK",
    PUSH_BIND = "PUSH_BIND",
    
    IDENTIFIER = "IDENTIFIER",
    NUMBER = "NUMBER",
    FLOAT = "FLOAT",
    STRING = "STRING",
    BIND = "BIND",
    
    COMMA = "COMMA",
    PERIOD = "PERIOD",
}